apiVersion: v1
kind: Secret
metadata:
  name: dhlsecret
type: Opaque
data:
  database: aWJtY2xvdWRkYg==
  dbuser: aWJtX2Nsb3VkX2Y5MmRlNTFhXzkwYjZfNDhjYl84NGQ2XzIwNzhmMGU5YzE2MQ==
  dbpass: ZGE3NThkYjBkNDNhMTg4YjAwNGYwOGNhZTU5MDZmYWMxYmUyZWFlMTUxYjM5MDE5ZTdmZTAzYTgxNTFiNjdkOQ==
  dbhost: MDFmZDBmZWMtMTk1Yy00MWYzLWIyZDAtMTFkZDI5MGUwNmNmLmJuMmEydmdkMDFyM2wwaGZtdmMwLmRhdGFiYXNlcy5hcHBkb21haW4uY2xvdWQ=
  dbport: MzA1Mzc=
  key: YS16aWhtZ3UtbXBjZDJncm5ucQ==
  token: ZnlMWlkpSmFzKzlidlNicCpU
  redis_host: ZGhsLXJlZGlzLW1hc3Rlci5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2Fs
  redis_port: NjM3OQ==
  redis_pass: NW1xTnljb043dw==
