apiVersion: apps/v1
kind: Deployment
metadata:
  name: dhl-trackntrace
  labels:
    app: dhl-trackntrace
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dhl-trackntrace
  template:
    metadata:
      name: dhl-trackntrace
      labels:
        app: dhl-trackntrace
    spec:
      containers:
      - name: dhl-trackntrace
        image: us.icr.io/dhl-global/dhl-trackntrace:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 6005
        env:
        - name: ORG_ID
          value: zihmgu
        - name: MQTT_APPID
          value: devappk8s
        - name: DEVICE_LIST
          value: forklift:ORDF99,anchor_device:anchor_tag_1
        - name: LOG_LEVEL
          value: "DEBUG"
        - name: SITE_CODE
          value: "ORD"
        - name: WEB_PORT
          value: "6005"
        - name: WEB_HOST
          value: "0.0.0.0"
        - name: DHL_URL
          value: "prod"
        - name: REDIS_HOST
          value: "dhl-redis-master.default.svc.cluster.local"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PWD
          value: "5mqNycoN7w"
        - name: USE_REDIS
          value: "T"
        
    
---

apiVersion: v1
kind: Service
metadata:
  name: dhl-trackntrace
  labels:
    app: dhl-trackntrace
spec:
  ports:
  - port: 6005
    targetPort: 6005
  selector:
    app: dhl-trackntrace

        
        

